### PR TITLE
maybe pst grammar didn't work

### PR DESCRIPTION
**Pull request by dove1413**
grammar update made it works

### CODE REVIEW

**Comment by starrify** [comment]
About this very line of change:
1. I agree that your code shall be working.
2. I don't think the original CSS selector is incorrect.
3. I have been using this tool and it's been working fine.
4. Could you please share some details if you have encountered issues with that specific line?

Thank you for the concern @d0ye.

**Comment by dove1413** [comment]
under python2.7

with BS4 
32, in attempt_login
    fkey = soup.select('input[name=fkey]')['value']
TypeError: list indices must be integers, not str

with BS3
32, in attempt_login
    fkey = soup.select('input[name=fkey]')['value']
TypeError: 'NoneType' object is not callable

I'm not familiar with BS and it's parser,Just try to use ,faced an issue ,did not really figure out why didn't work and made a quick fix.
If the original version worked fine with a default python 2x and pip install beautifulsoup4 ,then may don't need any change.

**Comment by starrify** [comment]
Please kindly notice that the original line was:

```
fkey = soup.select('input[name=fkey]')[0]['value']
```

**Comment by dove1413** [comment]
I know , I tried with bs3 didn't work and change the code at first, and install bs4 just uncomment the code I changed  so...😅 It works.  Thanks 4 figuring out :)

**Pull request closed without merging**
